import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { TopBar } from "@/components/TopBar";
import { listRecentReports, downloadPdfReport, downloadEditableReport } from "@/api/inspections";
import type { ReportHistoryEntry } from "@/types";

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function ReportsPage() {
  const [reports, setReports] = useState<ReportHistoryEntry[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    listRecentReports()
      .then(setReports)
      .catch(() => setError("Could not load report history. This view requires analytics access."));
  }, []);

  return (
    <>
      <TopBar title="Reports" />
      <div className="app-content">
        <div className="panel">
          <div className="panel-title">Recently Generated Reports</div>
          <p style={{ fontSize: 13, color: "var(--color-steel)" }}>
            Every PDF and DOCX generation is recorded to the audit log the moment it happens
            (see backend <code>AuditLogEntry action="REPORT_GENERATED"</code>) — this list reflects
            that log, not a separate report database.
          </p>
          {error && <div className="empty-state">{error}</div>}
          {!error && reports.length === 0 && (
            <div className="empty-state">No reports generated yet. Open an inspection and generate one.</div>
          )}
          {!error && reports.length > 0 && (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Format</th>
                  <th>Generated By</th>
                  <th>Generated At</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r, idx) => (
                  <tr key={`${r.inspectionId}-${idx}`}>
                    <td><Link to={`/inspections/${r.inspectionId}`}>{r.productName}</Link></td>
                    <td className="mono">{r.format.toUpperCase()}</td>
                    <td>{r.generatedBy.replace("_", " ")}</td>
                    <td className="mono">{new Date(r.generatedAt).toLocaleString()}</td>
                    <td>
                      <button
                        className="btn secondary"
                        style={{ padding: "4px 10px", fontSize: 12 }}
                        onClick={async () => {
                          const blob =
                            r.format === "pdf"
                              ? await downloadPdfReport(r.inspectionId)
                              : await downloadEditableReport(r.inspectionId);
                          triggerDownload(blob, `${r.inspectionId}.${r.format}`);
                        }}
                      >
                        Re-download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </>
  );
}
